version: "3.8"

services:
  nodejs_app:
    image: sahilvaidya13/credit_approval
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_NAME=credit_approval
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_HOST=mysql_db
      - DB_PORT=3306
    restart: always
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: credit_approval
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
